# Definitive Build Workflow - v4 (Verified)
# This workflow has been verified against the official GitHub Action documentation as of July 2025.
name: Build COD4 Cheat

on:
  # Enables the manual "Run workflow" button in the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Get your source code from the repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create a vcpkg manifest file to declare the d3dx9 dependency.
      - name: Create vcpkg.json
        run: |
          echo '{ "dependencies": [ "d3dx9" ] }' > vcpkg.json
        shell: pwsh

      # Step 3: Install the DirectX 9 dependency using the correct action.
      # THE FIX: Using version @v6 and the correct kebab-case parameter names.
      - name: Install Dependencies via vcpkg
        uses: microsoft/vcpkg-action@v6
        with:
          vcpkg-directory: ${{ runner.tool_cache }}/vcpkg
          vcpkg-json-glob: '**/vcpkg.json'

      # Step 4: Patch the source code to fix the missing C++ header.
      - name: Patch Common.hpp to include <chrono>
        run: |
          $content = Get-Content -Path Common.hpp -Raw
          "#include <chrono>`n$content" | Set-Content -Path Common.hpp -Force
        shell: pwsh

      # Step 5: Reliably set up the MSBuild environment.
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # Step 6: Build the project. MSBuild automatically uses vcpkg-installed libraries.
      - name: Build the Solution
        run: msbuild.exe "DX9-Cheat-Base.sln" /p:Configuration=Release /p:Platform=x86

      # Step 7: Upload the final .dll file as a downloadable artifact.
      - name: Upload Cheat DLL
        uses: actions/upload-artifact@v4
        with:
          name: Built-Cheat-DLL
          path: Release/DX9-Cheat-Base.dll
