# .github/workflows/build.yml

name: Build C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # CORRECTED STEP: Using a verified and publicly available action.
    # The previous action identifier was invalid. This one resolves correctly.
    - name: Install DirectX SDK
      uses: GRDigital/directx-sdk-action@v1
      with:
        platform: 'x86'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Build Solution
      run: |
        echo "[INFO] Starting MSBuild for DX9-Cheat-Base.sln with platform x86"
        msbuild.exe "DX9-Cheat-Base.sln" -p:Configuration=Release -p:Platform=x86
        echo "[SUCCESS] MSBuild finished."

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: COD4-Cheat-Release-DLL
        path: Release/DX9-Cheat-Base.dll
